/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.DefaultSchema;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.GithubBranchRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GithubBranch extends TableImpl<GithubBranchRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GITHUB_BRANCH</code>
     */
    public static final GithubBranch GITHUB_BRANCH = new GithubBranch();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<GithubBranchRecord> getRecordType() {
        return GithubBranchRecord.class;
    }

    /**
     * The column <code>GITHUB_BRANCH.NAME</code>.
     */
    public final TableField<GithubBranchRecord, String> NAME =
        createField(DSL.name("NAME"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>GITHUB_BRANCH.WEBSITE_INFO_ID</code>.
     */
    public final TableField<GithubBranchRecord, Integer> WEBSITE_INFO_ID =
        createField(DSL.name("WEBSITE_INFO_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    private GithubBranch(Name alias, Table<GithubBranchRecord> aliased) {
        this(alias, aliased, null);
    }

    private GithubBranch(Name alias, Table<GithubBranchRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>GITHUB_BRANCH</code> table reference
     */
    public GithubBranch(String alias) {
        this(DSL.name(alias), GITHUB_BRANCH);
    }

    /**
     * Create an aliased <code>GITHUB_BRANCH</code> table reference
     */
    public GithubBranch(Name alias) {
        this(alias, GITHUB_BRANCH);
    }

    /**
     * Create a <code>GITHUB_BRANCH</code> table reference
     */
    public GithubBranch() {
        this(DSL.name("GITHUB_BRANCH"), null);
    }

    public <O extends Record> GithubBranch(Table<O> child, ForeignKey<O, GithubBranchRecord> key) {
        super(child, key, GITHUB_BRANCH);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<GithubBranchRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_12;
    }

    @Override
    @NotNull
    public List<ForeignKey<GithubBranchRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_129);
    }

    private transient GithubInfo _githubInfo;

    /**
     * Get the implicit join path to the <code>PUBLIC.GITHUB_INFO</code> table.
     */
    public GithubInfo githubInfo() {
        if (_githubInfo == null) {
            _githubInfo = new GithubInfo(this, Keys.CONSTRAINT_129);
        }

        return _githubInfo;
    }

    @Override
    @NotNull
    public GithubBranch as(String alias) {
        return new GithubBranch(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public GithubBranch as(Name alias) {
        return new GithubBranch(alias, this);
    }

    @Override
    @NotNull
    public GithubBranch as(Table<?> alias) {
        return new GithubBranch(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubBranch rename(String name) {
        return new GithubBranch(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubBranch rename(Name name) {
        return new GithubBranch(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubBranch rename(Table<?> name) {
        return new GithubBranch(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
