/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.DefaultSchema;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.GithubInfoRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GithubInfo extends TableImpl<GithubInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GITHUB_INFO</code>
     */
    public static final GithubInfo GITHUB_INFO = new GithubInfo();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<GithubInfoRecord> getRecordType() {
        return GithubInfoRecord.class;
    }

    /**
     * The column <code>GITHUB_INFO.WEBSITE_INFO_ID</code>.
     */
    public final TableField<GithubInfoRecord, Integer> WEBSITE_INFO_ID =
        createField(DSL.name("WEBSITE_INFO_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>GITHUB_INFO.USER_NAME</code>.
     */
    public final TableField<GithubInfoRecord, String> USER_NAME =
        createField(DSL.name("USER_NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>GITHUB_INFO.REPOSITORY_NAME</code>.
     */
    public final TableField<GithubInfoRecord, String> REPOSITORY_NAME =
        createField(DSL.name("REPOSITORY_NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>GITHUB_INFO.LAST_ACTIVITY_DATE_TIME</code>.
     */
    public final TableField<GithubInfoRecord, LocalDateTime> LAST_ACTIVITY_DATE_TIME =
        createField(DSL.name("LAST_ACTIVITY_DATE_TIME"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private GithubInfo(Name alias, Table<GithubInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private GithubInfo(Name alias, Table<GithubInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>GITHUB_INFO</code> table reference
     */
    public GithubInfo(String alias) {
        this(DSL.name(alias), GITHUB_INFO);
    }

    /**
     * Create an aliased <code>GITHUB_INFO</code> table reference
     */
    public GithubInfo(Name alias) {
        this(alias, GITHUB_INFO);
    }

    /**
     * Create a <code>GITHUB_INFO</code> table reference
     */
    public GithubInfo() {
        this(DSL.name("GITHUB_INFO"), null);
    }

    public <O extends Record> GithubInfo(Table<O> child, ForeignKey<O, GithubInfoRecord> key) {
        super(child, key, GITHUB_INFO);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<GithubInfoRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D8;
    }

    @Override
    @NotNull
    public List<UniqueKey<GithubInfoRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.LINK_INFO_GIT_HUB_INFO);
    }

    @Override
    @NotNull
    public List<ForeignKey<GithubInfoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_D89);
    }

    private transient WebsiteInfo _websiteInfo;

    /**
     * Get the implicit join path to the <code>PUBLIC.WEBSITE_INFO</code> table.
     */
    public WebsiteInfo websiteInfo() {
        if (_websiteInfo == null) {
            _websiteInfo = new WebsiteInfo(this, Keys.CONSTRAINT_D89);
        }

        return _websiteInfo;
    }

    @Override
    @NotNull
    public GithubInfo as(String alias) {
        return new GithubInfo(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public GithubInfo as(Name alias) {
        return new GithubInfo(alias, this);
    }

    @Override
    @NotNull
    public GithubInfo as(Table<?> alias) {
        return new GithubInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubInfo rename(String name) {
        return new GithubInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubInfo rename(Name name) {
        return new GithubInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubInfo rename(Table<?> name) {
        return new GithubInfo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Integer, String, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
        Class<U> toType,
        Function4<? super Integer, ? super String, ? super String, ? super LocalDateTime, ? extends U> from
    ) {
        return convertFrom(toType, Records.mapping(from));
    }
}
