/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.DefaultSchema;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.StackOverflowAnswerRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class StackOverflowAnswer extends TableImpl<StackOverflowAnswerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>STACK_OVERFLOW_ANSWER</code>
     */
    public static final StackOverflowAnswer STACK_OVERFLOW_ANSWER = new StackOverflowAnswer();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<StackOverflowAnswerRecord> getRecordType() {
        return StackOverflowAnswerRecord.class;
    }

    /**
     * The column <code>STACK_OVERFLOW_ANSWER.ID</code>.
     */
    public final TableField<StackOverflowAnswerRecord, Integer> ID =
        createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>STACK_OVERFLOW_ANSWER.USER_NAME</code>.
     */
    public final TableField<StackOverflowAnswerRecord, String> USER_NAME =
        createField(DSL.name("USER_NAME"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>STACK_OVERFLOW_ANSWER.LAST_EDIT_DATE_TIME</code>.
     */
    public final TableField<StackOverflowAnswerRecord, LocalDateTime> LAST_EDIT_DATE_TIME =
        createField(DSL.name("LAST_EDIT_DATE_TIME"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>STACK_OVERFLOW_ANSWER.WEBSITE_INFO_ID</code>.
     */
    public final TableField<StackOverflowAnswerRecord, Integer> WEBSITE_INFO_ID =
        createField(DSL.name("WEBSITE_INFO_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    private StackOverflowAnswer(Name alias, Table<StackOverflowAnswerRecord> aliased) {
        this(alias, aliased, null);
    }

    private StackOverflowAnswer(Name alias, Table<StackOverflowAnswerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>STACK_OVERFLOW_ANSWER</code> table reference
     */
    public StackOverflowAnswer(String alias) {
        this(DSL.name(alias), STACK_OVERFLOW_ANSWER);
    }

    /**
     * Create an aliased <code>STACK_OVERFLOW_ANSWER</code> table reference
     */
    public StackOverflowAnswer(Name alias) {
        this(alias, STACK_OVERFLOW_ANSWER);
    }

    /**
     * Create a <code>STACK_OVERFLOW_ANSWER</code> table reference
     */
    public StackOverflowAnswer() {
        this(DSL.name("STACK_OVERFLOW_ANSWER"), null);
    }

    public <O extends Record> StackOverflowAnswer(Table<O> child, ForeignKey<O, StackOverflowAnswerRecord> key) {
        super(child, key, STACK_OVERFLOW_ANSWER);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<StackOverflowAnswerRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D3;
    }

    @Override
    @NotNull
    public List<ForeignKey<StackOverflowAnswerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_D33);
    }

    private transient StackoverflowInfo _stackoverflowInfo;

    /**
     * Get the implicit join path to the <code>PUBLIC.STACKOVERFLOW_INFO</code>
     * table.
     */
    public StackoverflowInfo stackoverflowInfo() {
        if (_stackoverflowInfo == null) {
            _stackoverflowInfo = new StackoverflowInfo(this, Keys.CONSTRAINT_D33);
        }

        return _stackoverflowInfo;
    }

    @Override
    @NotNull
    public StackOverflowAnswer as(String alias) {
        return new StackOverflowAnswer(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public StackOverflowAnswer as(Name alias) {
        return new StackOverflowAnswer(alias, this);
    }

    @Override
    @NotNull
    public StackOverflowAnswer as(Table<?> alias) {
        return new StackOverflowAnswer(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackOverflowAnswer rename(String name) {
        return new StackOverflowAnswer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackOverflowAnswer rename(Name name) {
        return new StackOverflowAnswer(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackOverflowAnswer rename(Table<?> name) {
        return new StackOverflowAnswer(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Integer, String, LocalDateTime, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super LocalDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
        Class<U> toType,
        Function4<? super Integer, ? super String, ? super LocalDateTime, ? super Integer, ? extends U> from
    ) {
        return convertFrom(toType, Records.mapping(from));
    }
}
