/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.DefaultSchema;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.StackOverflowCommentRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class StackOverflowComment extends TableImpl<StackOverflowCommentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>STACK_OVERFLOW_COMMENT</code>
     */
    public static final StackOverflowComment STACK_OVERFLOW_COMMENT = new StackOverflowComment();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<StackOverflowCommentRecord> getRecordType() {
        return StackOverflowCommentRecord.class;
    }

    /**
     * The column <code>STACK_OVERFLOW_COMMENT.ID</code>.
     */
    public final TableField<StackOverflowCommentRecord, Integer> ID =
        createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>STACK_OVERFLOW_COMMENT.WEBSITE_INFO_ID</code>.
     */
    public final TableField<StackOverflowCommentRecord, Integer> WEBSITE_INFO_ID =
        createField(DSL.name("WEBSITE_INFO_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    private StackOverflowComment(Name alias, Table<StackOverflowCommentRecord> aliased) {
        this(alias, aliased, null);
    }

    private StackOverflowComment(Name alias, Table<StackOverflowCommentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>STACK_OVERFLOW_COMMENT</code> table reference
     */
    public StackOverflowComment(String alias) {
        this(DSL.name(alias), STACK_OVERFLOW_COMMENT);
    }

    /**
     * Create an aliased <code>STACK_OVERFLOW_COMMENT</code> table reference
     */
    public StackOverflowComment(Name alias) {
        this(alias, STACK_OVERFLOW_COMMENT);
    }

    /**
     * Create a <code>STACK_OVERFLOW_COMMENT</code> table reference
     */
    public StackOverflowComment() {
        this(DSL.name("STACK_OVERFLOW_COMMENT"), null);
    }

    public <O extends Record> StackOverflowComment(Table<O> child, ForeignKey<O, StackOverflowCommentRecord> key) {
        super(child, key, STACK_OVERFLOW_COMMENT);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<StackOverflowCommentRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_F;
    }

    @Override
    @NotNull
    public List<ForeignKey<StackOverflowCommentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_FF);
    }

    private transient StackoverflowInfo _stackoverflowInfo;

    /**
     * Get the implicit join path to the <code>PUBLIC.STACKOVERFLOW_INFO</code>
     * table.
     */
    public StackoverflowInfo stackoverflowInfo() {
        if (_stackoverflowInfo == null) {
            _stackoverflowInfo = new StackoverflowInfo(this, Keys.CONSTRAINT_FF);
        }

        return _stackoverflowInfo;
    }

    @Override
    @NotNull
    public StackOverflowComment as(String alias) {
        return new StackOverflowComment(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public StackOverflowComment as(Name alias) {
        return new StackOverflowComment(alias, this);
    }

    @Override
    @NotNull
    public StackOverflowComment as(Table<?> alias) {
        return new StackOverflowComment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackOverflowComment rename(String name) {
        return new StackOverflowComment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackOverflowComment rename(Name name) {
        return new StackOverflowComment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackOverflowComment rename(Table<?> name) {
        return new StackOverflowComment(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
