/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.DefaultSchema;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.StackoverflowInfoRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class StackoverflowInfo extends TableImpl<StackoverflowInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>STACKOVERFLOW_INFO</code>
     */
    public static final StackoverflowInfo STACKOVERFLOW_INFO = new StackoverflowInfo();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<StackoverflowInfoRecord> getRecordType() {
        return StackoverflowInfoRecord.class;
    }

    /**
     * The column <code>STACKOVERFLOW_INFO.WEBSITE_INFO_ID</code>.
     */
    public final TableField<StackoverflowInfoRecord, Integer> WEBSITE_INFO_ID =
        createField(DSL.name("WEBSITE_INFO_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>STACKOVERFLOW_INFO.QUESTION_ID</code>.
     */
    public final TableField<StackoverflowInfoRecord, Integer> QUESTION_ID =
        createField(DSL.name("QUESTION_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    private StackoverflowInfo(Name alias, Table<StackoverflowInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private StackoverflowInfo(Name alias, Table<StackoverflowInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>STACKOVERFLOW_INFO</code> table reference
     */
    public StackoverflowInfo(String alias) {
        this(DSL.name(alias), STACKOVERFLOW_INFO);
    }

    /**
     * Create an aliased <code>STACKOVERFLOW_INFO</code> table reference
     */
    public StackoverflowInfo(Name alias) {
        this(alias, STACKOVERFLOW_INFO);
    }

    /**
     * Create a <code>STACKOVERFLOW_INFO</code> table reference
     */
    public StackoverflowInfo() {
        this(DSL.name("STACKOVERFLOW_INFO"), null);
    }

    public <O extends Record> StackoverflowInfo(Table<O> child, ForeignKey<O, StackoverflowInfoRecord> key) {
        super(child, key, STACKOVERFLOW_INFO);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<StackoverflowInfoRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    @Override
    @NotNull
    public List<UniqueKey<StackoverflowInfoRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.LINK_INFO_STACK_OVERFLOW_INFO);
    }

    @Override
    @NotNull
    public List<ForeignKey<StackoverflowInfoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_92);
    }

    private transient WebsiteInfo _websiteInfo;

    /**
     * Get the implicit join path to the <code>PUBLIC.WEBSITE_INFO</code> table.
     */
    public WebsiteInfo websiteInfo() {
        if (_websiteInfo == null) {
            _websiteInfo = new WebsiteInfo(this, Keys.CONSTRAINT_92);
        }

        return _websiteInfo;
    }

    @Override
    @NotNull
    public StackoverflowInfo as(String alias) {
        return new StackoverflowInfo(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public StackoverflowInfo as(Name alias) {
        return new StackoverflowInfo(alias, this);
    }

    @Override
    @NotNull
    public StackoverflowInfo as(Table<?> alias) {
        return new StackoverflowInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackoverflowInfo rename(String name) {
        return new StackoverflowInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackoverflowInfo rename(Name name) {
        return new StackoverflowInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public StackoverflowInfo rename(Table<?> name) {
        return new StackoverflowInfo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
