/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.DefaultSchema;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.TrackedLinkRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TrackedLink extends TableImpl<TrackedLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TRACKED_LINK</code>
     */
    public static final TrackedLink TRACKED_LINK = new TrackedLink();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<TrackedLinkRecord> getRecordType() {
        return TrackedLinkRecord.class;
    }

    /**
     * The column <code>TRACKED_LINK.ID</code>.
     */
    public final TableField<TrackedLinkRecord, Integer> ID =
        createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>TRACKED_LINK.WEBSITE_INFO_ID</code>.
     */
    public final TableField<TrackedLinkRecord, Integer> WEBSITE_INFO_ID =
        createField(DSL.name("WEBSITE_INFO_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>TRACKED_LINK.CHAT_ID</code>.
     */
    public final TableField<TrackedLinkRecord, Integer> CHAT_ID =
        createField(DSL.name("CHAT_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    private TrackedLink(Name alias, Table<TrackedLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private TrackedLink(Name alias, Table<TrackedLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>TRACKED_LINK</code> table reference
     */
    public TrackedLink(String alias) {
        this(DSL.name(alias), TRACKED_LINK);
    }

    /**
     * Create an aliased <code>TRACKED_LINK</code> table reference
     */
    public TrackedLink(Name alias) {
        this(alias, TRACKED_LINK);
    }

    /**
     * Create a <code>TRACKED_LINK</code> table reference
     */
    public TrackedLink() {
        this(DSL.name("TRACKED_LINK"), null);
    }

    public <O extends Record> TrackedLink(Table<O> child, ForeignKey<O, TrackedLinkRecord> key) {
        super(child, key, TRACKED_LINK);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<TrackedLinkRecord, Integer> getIdentity() {
        return (Identity<TrackedLinkRecord, Integer>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<TrackedLinkRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3;
    }

    @Override
    @NotNull
    public List<ForeignKey<TrackedLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_36, Keys.CONSTRAINT_368);
    }

    private transient WebsiteInfo _websiteInfo;
    private transient Chat _chat;

    /**
     * Get the implicit join path to the <code>PUBLIC.WEBSITE_INFO</code> table.
     */
    public WebsiteInfo websiteInfo() {
        if (_websiteInfo == null) {
            _websiteInfo = new WebsiteInfo(this, Keys.CONSTRAINT_36);
        }

        return _websiteInfo;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.CHAT</code> table.
     */
    public Chat chat() {
        if (_chat == null) {
            _chat = new Chat(this, Keys.CONSTRAINT_368);
        }

        return _chat;
    }

    @Override
    @NotNull
    public TrackedLink as(String alias) {
        return new TrackedLink(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public TrackedLink as(Name alias) {
        return new TrackedLink(alias, this);
    }

    @Override
    @NotNull
    public TrackedLink as(Table<?> alias) {
        return new TrackedLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TrackedLink rename(String name) {
        return new TrackedLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TrackedLink rename(Name name) {
        return new TrackedLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TrackedLink rename(Table<?> name) {
        return new TrackedLink(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
        Class<U> toType,
        Function3<? super Integer, ? super Integer, ? super Integer, ? extends U> from
    ) {
        return convertFrom(toType, Records.mapping(from));
    }
}
