/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.DefaultSchema;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.WebsiteInfoRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WebsiteInfo extends TableImpl<WebsiteInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>WEBSITE_INFO</code>
     */
    public static final WebsiteInfo WEBSITE_INFO = new WebsiteInfo();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<WebsiteInfoRecord> getRecordType() {
        return WebsiteInfoRecord.class;
    }

    /**
     * The column <code>WEBSITE_INFO.ID</code>.
     */
    public final TableField<WebsiteInfoRecord, Integer> ID =
        createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>WEBSITE_INFO.TYPE_ID</code>.
     */
    public final TableField<WebsiteInfoRecord, Integer> TYPE_ID =
        createField(DSL.name("TYPE_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>WEBSITE_INFO.LAST_UPDATE_DATE_TIME</code>.
     */
    public final TableField<WebsiteInfoRecord, LocalDateTime> LAST_UPDATE_DATE_TIME =
        createField(DSL.name("LAST_UPDATE_DATE_TIME"),
            SQLDataType.LOCALDATETIME(6).nullable(false)
                .defaultValue(DSL.field(DSL.raw("LOCALTIMESTAMP"), SQLDataType.LOCALDATETIME)),
            this,
            ""
        );

    private WebsiteInfo(Name alias, Table<WebsiteInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private WebsiteInfo(Name alias, Table<WebsiteInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>WEBSITE_INFO</code> table reference
     */
    public WebsiteInfo(String alias) {
        this(DSL.name(alias), WEBSITE_INFO);
    }

    /**
     * Create an aliased <code>WEBSITE_INFO</code> table reference
     */
    public WebsiteInfo(Name alias) {
        this(alias, WEBSITE_INFO);
    }

    /**
     * Create a <code>WEBSITE_INFO</code> table reference
     */
    public WebsiteInfo() {
        this(DSL.name("WEBSITE_INFO"), null);
    }

    public <O extends Record> WebsiteInfo(Table<O> child, ForeignKey<O, WebsiteInfoRecord> key) {
        super(child, key, WEBSITE_INFO);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<WebsiteInfoRecord, Integer> getIdentity() {
        return (Identity<WebsiteInfoRecord, Integer>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<WebsiteInfoRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    @Override
    @NotNull
    public List<ForeignKey<WebsiteInfoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_41);
    }

    private transient WebsiteInfoType _websiteInfoType;

    /**
     * Get the implicit join path to the <code>PUBLIC.WEBSITE_INFO_TYPE</code>
     * table.
     */
    public WebsiteInfoType websiteInfoType() {
        if (_websiteInfoType == null) {
            _websiteInfoType = new WebsiteInfoType(this, Keys.CONSTRAINT_41);
        }

        return _websiteInfoType;
    }

    @Override
    @NotNull
    public WebsiteInfo as(String alias) {
        return new WebsiteInfo(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public WebsiteInfo as(Name alias) {
        return new WebsiteInfo(alias, this);
    }

    @Override
    @NotNull
    public WebsiteInfo as(Table<?> alias) {
        return new WebsiteInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public WebsiteInfo rename(String name) {
        return new WebsiteInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public WebsiteInfo rename(Name name) {
        return new WebsiteInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public WebsiteInfo rename(Table<?> name) {
        return new WebsiteInfo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super Integer, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
        Class<U> toType,
        Function3<? super Integer, ? super Integer, ? super LocalDateTime, ? extends U> from
    ) {
        return convertFrom(toType, Records.mapping(from));
    }
}
