/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables;

import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.DefaultSchema;
import ru.tinkoff.edu.java.scrapper.domain.jooq.Keys;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.WebsiteInfoTypeRecord;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WebsiteInfoType extends TableImpl<WebsiteInfoTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>WEBSITE_INFO_TYPE</code>
     */
    public static final WebsiteInfoType WEBSITE_INFO_TYPE = new WebsiteInfoType();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<WebsiteInfoTypeRecord> getRecordType() {
        return WebsiteInfoTypeRecord.class;
    }

    /**
     * The column <code>WEBSITE_INFO_TYPE.ID</code>.
     */
    public final TableField<WebsiteInfoTypeRecord, Integer> ID =
        createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>WEBSITE_INFO_TYPE.NAME</code>.
     */
    public final TableField<WebsiteInfoTypeRecord, String> NAME =
        createField(DSL.name("NAME"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private WebsiteInfoType(Name alias, Table<WebsiteInfoTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private WebsiteInfoType(Name alias, Table<WebsiteInfoTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>WEBSITE_INFO_TYPE</code> table reference
     */
    public WebsiteInfoType(String alias) {
        this(DSL.name(alias), WEBSITE_INFO_TYPE);
    }

    /**
     * Create an aliased <code>WEBSITE_INFO_TYPE</code> table reference
     */
    public WebsiteInfoType(Name alias) {
        this(alias, WEBSITE_INFO_TYPE);
    }

    /**
     * Create a <code>WEBSITE_INFO_TYPE</code> table reference
     */
    public WebsiteInfoType() {
        this(DSL.name("WEBSITE_INFO_TYPE"), null);
    }

    public <O extends Record> WebsiteInfoType(Table<O> child, ForeignKey<O, WebsiteInfoTypeRecord> key) {
        super(child, key, WEBSITE_INFO_TYPE);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<WebsiteInfoTypeRecord, Integer> getIdentity() {
        return (Identity<WebsiteInfoTypeRecord, Integer>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<WebsiteInfoTypeRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D;
    }

    @Override
    @NotNull
    public WebsiteInfoType as(String alias) {
        return new WebsiteInfoType(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public WebsiteInfoType as(Name alias) {
        return new WebsiteInfoType(alias, this);
    }

    @Override
    @NotNull
    public WebsiteInfoType as(Table<?> alias) {
        return new WebsiteInfoType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public WebsiteInfoType rename(String name) {
        return new WebsiteInfoType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public WebsiteInfoType rename(Name name) {
        return new WebsiteInfoType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public WebsiteInfoType rename(Table<?> name) {
        return new WebsiteInfoType(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
