/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.GithubBranch;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GithubBranchRecord extends UpdatableRecordImpl<GithubBranchRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GITHUB_BRANCH.NAME</code>.
     */
    public void setName(@NotNull String value) {
        set(0, value);
    }

    /**
     * Getter for <code>GITHUB_BRANCH.NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 40)
    @NotNull
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>GITHUB_BRANCH.WEBSITE_INFO_ID</code>.
     */
    public void setWebsiteInfoId(@NotNull Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>GITHUB_BRANCH.WEBSITE_INFO_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getWebsiteInfoId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return GithubBranch.GITHUB_BRANCH.NAME;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return GithubBranch.GITHUB_BRANCH.WEBSITE_INFO_ID;
    }

    @Override
    @NotNull
    public String component1() {
        return getName();
    }

    @Override
    @NotNull
    public Integer component2() {
        return getWebsiteInfoId();
    }

    @Override
    @NotNull
    public String value1() {
        return getName();
    }

    @Override
    @NotNull
    public Integer value2() {
        return getWebsiteInfoId();
    }

    @Override
    @NotNull
    public GithubBranchRecord value1(@NotNull String value) {
        setName(value);
        return this;
    }

    @Override
    @NotNull
    public GithubBranchRecord value2(@NotNull Integer value) {
        setWebsiteInfoId(value);
        return this;
    }

    @Override
    @NotNull
    public GithubBranchRecord values(@NotNull String value1, @NotNull Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GithubBranchRecord
     */
    public GithubBranchRecord() {
        super(GithubBranch.GITHUB_BRANCH);
    }

    /**
     * Create a detached, initialised GithubBranchRecord
     */
    @ConstructorProperties({"name", "websiteInfoId"})
    public GithubBranchRecord(@NotNull String name, @NotNull Integer websiteInfoId) {
        super(GithubBranch.GITHUB_BRANCH);

        setName(name);
        setWebsiteInfoId(websiteInfoId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GithubBranchRecord
     */
    public GithubBranchRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.GithubBranch value) {
        super(GithubBranch.GITHUB_BRANCH);

        if (value != null) {
            setName(value.getName());
            setWebsiteInfoId(value.getWebsiteInfoId());
            resetChangedOnNotNull();
        }
    }
}
