/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;

import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.StackOverflowComment;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class StackOverflowCommentRecord extends UpdatableRecordImpl<StackOverflowCommentRecord>
    implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>STACK_OVERFLOW_COMMENT.ID</code>.
     */
    public void setId(@NotNull Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>STACK_OVERFLOW_COMMENT.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>STACK_OVERFLOW_COMMENT.WEBSITE_INFO_ID</code>.
     */
    public void setWebsiteInfoId(@NotNull Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>STACK_OVERFLOW_COMMENT.WEBSITE_INFO_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getWebsiteInfoId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return StackOverflowComment.STACK_OVERFLOW_COMMENT.ID;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return StackOverflowComment.STACK_OVERFLOW_COMMENT.WEBSITE_INFO_ID;
    }

    @Override
    @NotNull
    public Integer component1() {
        return getId();
    }

    @Override
    @NotNull
    public Integer component2() {
        return getWebsiteInfoId();
    }

    @Override
    @NotNull
    public Integer value1() {
        return getId();
    }

    @Override
    @NotNull
    public Integer value2() {
        return getWebsiteInfoId();
    }

    @Override
    @NotNull
    public StackOverflowCommentRecord value1(@NotNull Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public StackOverflowCommentRecord value2(@NotNull Integer value) {
        setWebsiteInfoId(value);
        return this;
    }

    @Override
    @NotNull
    public StackOverflowCommentRecord values(@NotNull Integer value1, @NotNull Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StackOverflowCommentRecord
     */
    public StackOverflowCommentRecord() {
        super(StackOverflowComment.STACK_OVERFLOW_COMMENT);
    }

    /**
     * Create a detached, initialised StackOverflowCommentRecord
     */
    @ConstructorProperties({"id", "websiteInfoId"})
    public StackOverflowCommentRecord(@NotNull Integer id, @NotNull Integer websiteInfoId) {
        super(StackOverflowComment.STACK_OVERFLOW_COMMENT);

        setId(id);
        setWebsiteInfoId(websiteInfoId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised StackOverflowCommentRecord
     */
    public StackOverflowCommentRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.StackOverflowComment value) {
        super(StackOverflowComment.STACK_OVERFLOW_COMMENT);

        if (value != null) {
            setId(value.getId());
            setWebsiteInfoId(value.getWebsiteInfoId());
            resetChangedOnNotNull();
        }
    }
}
