/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;

import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.TrackedLink;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TrackedLinkRecord extends UpdatableRecordImpl<TrackedLinkRecord>
    implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TRACKED_LINK.ID</code>.
     */
    public void setId(@Nullable Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TRACKED_LINK.ID</code>.
     */
    @Nullable
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TRACKED_LINK.WEBSITE_INFO_ID</code>.
     */
    public void setWebsiteInfoId(@NotNull Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>TRACKED_LINK.WEBSITE_INFO_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getWebsiteInfoId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>TRACKED_LINK.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>TRACKED_LINK.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getChatId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return TrackedLink.TRACKED_LINK.ID;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return TrackedLink.TRACKED_LINK.WEBSITE_INFO_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return TrackedLink.TRACKED_LINK.CHAT_ID;
    }

    @Override
    @Nullable
    public Integer component1() {
        return getId();
    }

    @Override
    @NotNull
    public Integer component2() {
        return getWebsiteInfoId();
    }

    @Override
    @NotNull
    public Integer component3() {
        return getChatId();
    }

    @Override
    @Nullable
    public Integer value1() {
        return getId();
    }

    @Override
    @NotNull
    public Integer value2() {
        return getWebsiteInfoId();
    }

    @Override
    @NotNull
    public Integer value3() {
        return getChatId();
    }

    @Override
    @NotNull
    public TrackedLinkRecord value1(@Nullable Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public TrackedLinkRecord value2(@NotNull Integer value) {
        setWebsiteInfoId(value);
        return this;
    }

    @Override
    @NotNull
    public TrackedLinkRecord value3(@NotNull Integer value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public TrackedLinkRecord values(@Nullable Integer value1, @NotNull Integer value2, @NotNull Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackedLinkRecord
     */
    public TrackedLinkRecord() {
        super(TrackedLink.TRACKED_LINK);
    }

    /**
     * Create a detached, initialised TrackedLinkRecord
     */
    @ConstructorProperties({"id", "websiteInfoId", "chatId"})
    public TrackedLinkRecord(@Nullable Integer id, @NotNull Integer websiteInfoId, @NotNull Integer chatId) {
        super(TrackedLink.TRACKED_LINK);

        setId(id);
        setWebsiteInfoId(websiteInfoId);
        setChatId(chatId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TrackedLinkRecord
     */
    public TrackedLinkRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.TrackedLink value) {
        super(TrackedLink.TRACKED_LINK);

        if (value != null) {
            setId(value.getId());
            setWebsiteInfoId(value.getWebsiteInfoId());
            setChatId(value.getChatId());
            resetChangedOnNotNull();
        }
    }
}
