/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GithubInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer websiteInfoId;
    private String userName;
    private String repositoryName;
    private LocalDateTime lastActivityDateTime;

    public GithubInfo() {
    }

    public GithubInfo(GithubInfo value) {
        this.websiteInfoId = value.websiteInfoId;
        this.userName = value.userName;
        this.repositoryName = value.repositoryName;
        this.lastActivityDateTime = value.lastActivityDateTime;
    }

    @ConstructorProperties({"websiteInfoId", "userName", "repositoryName", "lastActivityDateTime"})
    public GithubInfo(
        @NotNull Integer websiteInfoId,
        @NotNull String userName,
        @NotNull String repositoryName,
        @NotNull LocalDateTime lastActivityDateTime
    ) {
        this.websiteInfoId = websiteInfoId;
        this.userName = userName;
        this.repositoryName = repositoryName;
        this.lastActivityDateTime = lastActivityDateTime;
    }

    /**
     * Getter for <code>GITHUB_INFO.WEBSITE_INFO_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getWebsiteInfoId() {
        return this.websiteInfoId;
    }

    /**
     * Setter for <code>GITHUB_INFO.WEBSITE_INFO_ID</code>.
     */
    public void setWebsiteInfoId(@NotNull Integer websiteInfoId) {
        this.websiteInfoId = websiteInfoId;
    }

    /**
     * Getter for <code>GITHUB_INFO.USER_NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>GITHUB_INFO.USER_NAME</code>.
     */
    public void setUserName(@NotNull String userName) {
        this.userName = userName;
    }

    /**
     * Getter for <code>GITHUB_INFO.REPOSITORY_NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getRepositoryName() {
        return this.repositoryName;
    }

    /**
     * Setter for <code>GITHUB_INFO.REPOSITORY_NAME</code>.
     */
    public void setRepositoryName(@NotNull String repositoryName) {
        this.repositoryName = repositoryName;
    }

    /**
     * Getter for <code>GITHUB_INFO.LAST_ACTIVITY_DATE_TIME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public LocalDateTime getLastActivityDateTime() {
        return this.lastActivityDateTime;
    }

    /**
     * Setter for <code>GITHUB_INFO.LAST_ACTIVITY_DATE_TIME</code>.
     */
    public void setLastActivityDateTime(@NotNull LocalDateTime lastActivityDateTime) {
        this.lastActivityDateTime = lastActivityDateTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final GithubInfo other = (GithubInfo) obj;
        if (this.websiteInfoId == null) {
            if (other.websiteInfoId != null) {
                return false;
            }
        } else if (!this.websiteInfoId.equals(other.websiteInfoId)) {
            return false;
        }
        if (this.userName == null) {
            if (other.userName != null) {
                return false;
            }
        } else if (!this.userName.equals(other.userName)) {
            return false;
        }
        if (this.repositoryName == null) {
            if (other.repositoryName != null) {
                return false;
            }
        } else if (!this.repositoryName.equals(other.repositoryName)) {
            return false;
        }
        if (this.lastActivityDateTime == null) {
            if (other.lastActivityDateTime != null) {
                return false;
            }
        } else if (!this.lastActivityDateTime.equals(other.lastActivityDateTime)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.websiteInfoId == null) ? 0 : this.websiteInfoId.hashCode());
        result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
        result = prime * result + ((this.repositoryName == null) ? 0 : this.repositoryName.hashCode());
        result = prime * result + ((this.lastActivityDateTime == null) ? 0 : this.lastActivityDateTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GithubInfo (");

        sb.append(websiteInfoId);
        sb.append(", ").append(userName);
        sb.append(", ").append(repositoryName);
        sb.append(", ").append(lastActivityDateTime);

        sb.append(")");
        return sb.toString();
    }
}
