/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GithubBranch implements Serializable {

    private static final long serialVersionUID = 1L;

    private String name;
    private Integer websiteInfoId;

    public GithubBranch() {
    }

    public GithubBranch(GithubBranch value) {
        this.name = value.name;
        this.websiteInfoId = value.websiteInfoId;
    }

    @ConstructorProperties({"name", "websiteInfoId"})
    public GithubBranch(
        @NotNull String name,
        @NotNull Integer websiteInfoId
    ) {
        this.name = name;
        this.websiteInfoId = websiteInfoId;
    }

    /**
     * Getter for <code>GITHUB_BRANCH.NAME</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 40)
    @NotNull
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>GITHUB_BRANCH.NAME</code>.
     */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    /**
     * Getter for <code>GITHUB_BRANCH.WEBSITE_INFO_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getWebsiteInfoId() {
        return this.websiteInfoId;
    }

    /**
     * Setter for <code>GITHUB_BRANCH.WEBSITE_INFO_ID</code>.
     */
    public void setWebsiteInfoId(@NotNull Integer websiteInfoId) {
        this.websiteInfoId = websiteInfoId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final GithubBranch other = (GithubBranch) obj;
        if (this.name == null) {
            if (other.name != null) {
                return false;
            }
        } else if (!this.name.equals(other.name)) {
            return false;
        }
        if (this.websiteInfoId == null) {
            if (other.websiteInfoId != null) {
                return false;
            }
        } else if (!this.websiteInfoId.equals(other.websiteInfoId)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.websiteInfoId == null) ? 0 : this.websiteInfoId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GithubBranch (");

        sb.append(name);
        sb.append(", ").append(websiteInfoId);

        sb.append(")");
        return sb.toString();
    }
}
