/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class StackOverflowComment implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer websiteInfoId;

    public StackOverflowComment() {
    }

    public StackOverflowComment(StackOverflowComment value) {
        this.id = value.id;
        this.websiteInfoId = value.websiteInfoId;
    }

    @ConstructorProperties({"id", "websiteInfoId"})
    public StackOverflowComment(
        @NotNull Integer id,
        @NotNull Integer websiteInfoId
    ) {
        this.id = id;
        this.websiteInfoId = websiteInfoId;
    }

    /**
     * Getter for <code>STACK_OVERFLOW_COMMENT.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>STACK_OVERFLOW_COMMENT.ID</code>.
     */
    public void setId(@NotNull Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>STACK_OVERFLOW_COMMENT.WEBSITE_INFO_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getWebsiteInfoId() {
        return this.websiteInfoId;
    }

    /**
     * Setter for <code>STACK_OVERFLOW_COMMENT.WEBSITE_INFO_ID</code>.
     */
    public void setWebsiteInfoId(@NotNull Integer websiteInfoId) {
        this.websiteInfoId = websiteInfoId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final StackOverflowComment other = (StackOverflowComment) obj;
        if (this.id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!this.id.equals(other.id)) {
            return false;
        }
        if (this.websiteInfoId == null) {
            if (other.websiteInfoId != null) {
                return false;
            }
        } else if (!this.websiteInfoId.equals(other.websiteInfoId)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.websiteInfoId == null) ? 0 : this.websiteInfoId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StackOverflowComment (");

        sb.append(id);
        sb.append(", ").append(websiteInfoId);

        sb.append(")");
        return sb.toString();
    }
}
