/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WebsiteInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer typeId;
    private LocalDateTime lastUpdateDateTime;

    public WebsiteInfo() {
    }

    public WebsiteInfo(WebsiteInfo value) {
        this.id = value.id;
        this.typeId = value.typeId;
        this.lastUpdateDateTime = value.lastUpdateDateTime;
    }

    @ConstructorProperties({"id", "typeId", "lastUpdateDateTime"})
    public WebsiteInfo(
        @Nullable Integer id,
        @NotNull Integer typeId,
        @Nullable LocalDateTime lastUpdateDateTime
    ) {
        this.id = id;
        this.typeId = typeId;
        this.lastUpdateDateTime = lastUpdateDateTime;
    }

    /**
     * Getter for <code>WEBSITE_INFO.ID</code>.
     */
    @Nullable
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>WEBSITE_INFO.ID</code>.
     */
    public void setId(@Nullable Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>WEBSITE_INFO.TYPE_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getTypeId() {
        return this.typeId;
    }

    /**
     * Setter for <code>WEBSITE_INFO.TYPE_ID</code>.
     */
    public void setTypeId(@NotNull Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * Getter for <code>WEBSITE_INFO.LAST_UPDATE_DATE_TIME</code>.
     */
    @Nullable
    public LocalDateTime getLastUpdateDateTime() {
        return this.lastUpdateDateTime;
    }

    /**
     * Setter for <code>WEBSITE_INFO.LAST_UPDATE_DATE_TIME</code>.
     */
    public void setLastUpdateDateTime(@Nullable LocalDateTime lastUpdateDateTime) {
        this.lastUpdateDateTime = lastUpdateDateTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final WebsiteInfo other = (WebsiteInfo) obj;
        if (this.id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!this.id.equals(other.id)) {
            return false;
        }
        if (this.typeId == null) {
            if (other.typeId != null) {
                return false;
            }
        } else if (!this.typeId.equals(other.typeId)) {
            return false;
        }
        if (this.lastUpdateDateTime == null) {
            if (other.lastUpdateDateTime != null) {
                return false;
            }
        } else if (!this.lastUpdateDateTime.equals(other.lastUpdateDateTime)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.typeId == null) ? 0 : this.typeId.hashCode());
        result = prime * result + ((this.lastUpdateDateTime == null) ? 0 : this.lastUpdateDateTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WebsiteInfo (");

        sb.append(id);
        sb.append(", ").append(typeId);
        sb.append(", ").append(lastUpdateDateTime);

        sb.append(")");
        return sb.toString();
    }
}
