/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq;

import java.util.Arrays;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Chat;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.GithubBranch;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.GithubCommit;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.GithubInfo;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.StackOverflowAnswer;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.StackOverflowComment;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.StackoverflowInfo;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.TrackedLink;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.WebsiteInfo;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.WebsiteInfoType;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>CHAT</code>.
     */
    public final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>GITHUB_BRANCH</code>.
     */
    public final GithubBranch GITHUB_BRANCH = GithubBranch.GITHUB_BRANCH;

    /**
     * The table <code>GITHUB_COMMIT</code>.
     */
    public final GithubCommit GITHUB_COMMIT = GithubCommit.GITHUB_COMMIT;

    /**
     * The table <code>GITHUB_INFO</code>.
     */
    public final GithubInfo GITHUB_INFO = GithubInfo.GITHUB_INFO;

    /**
     * The table <code>STACK_OVERFLOW_ANSWER</code>.
     */
    public final StackOverflowAnswer STACK_OVERFLOW_ANSWER = StackOverflowAnswer.STACK_OVERFLOW_ANSWER;

    /**
     * The table <code>STACK_OVERFLOW_COMMENT</code>.
     */
    public final StackOverflowComment STACK_OVERFLOW_COMMENT = StackOverflowComment.STACK_OVERFLOW_COMMENT;

    /**
     * The table <code>STACKOVERFLOW_INFO</code>.
     */
    public final StackoverflowInfo STACKOVERFLOW_INFO = StackoverflowInfo.STACKOVERFLOW_INFO;

    /**
     * The table <code>TRACKED_LINK</code>.
     */
    public final TrackedLink TRACKED_LINK = TrackedLink.TRACKED_LINK;

    /**
     * The table <code>WEBSITE_INFO</code>.
     */
    public final WebsiteInfo WEBSITE_INFO = WebsiteInfo.WEBSITE_INFO;

    /**
     * The table <code>WEBSITE_INFO_TYPE</code>.
     */
    public final WebsiteInfoType WEBSITE_INFO_TYPE = WebsiteInfoType.WEBSITE_INFO_TYPE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }

    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Chat.CHAT,
            GithubBranch.GITHUB_BRANCH,
            GithubCommit.GITHUB_COMMIT,
            GithubInfo.GITHUB_INFO,
            StackOverflowAnswer.STACK_OVERFLOW_ANSWER,
            StackOverflowComment.STACK_OVERFLOW_COMMENT,
            StackoverflowInfo.STACKOVERFLOW_INFO,
            TrackedLink.TRACKED_LINK,
            WebsiteInfo.WEBSITE_INFO,
            WebsiteInfoType.WEBSITE_INFO_TYPE
        );
    }
}
