/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq;

import javax.annotation.processing.Generated;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Chat;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.GithubBranch;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.GithubCommit;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.GithubInfo;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.StackOverflowAnswer;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.StackOverflowComment;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.StackoverflowInfo;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.TrackedLink;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.WebsiteInfo;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.WebsiteInfoType;

/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>CHAT</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>GITHUB_BRANCH</code>.
     */
    public static final GithubBranch GITHUB_BRANCH = GithubBranch.GITHUB_BRANCH;

    /**
     * The table <code>GITHUB_COMMIT</code>.
     */
    public static final GithubCommit GITHUB_COMMIT = GithubCommit.GITHUB_COMMIT;

    /**
     * The table <code>GITHUB_INFO</code>.
     */
    public static final GithubInfo GITHUB_INFO = GithubInfo.GITHUB_INFO;

    /**
     * The table <code>STACK_OVERFLOW_ANSWER</code>.
     */
    public static final StackOverflowAnswer STACK_OVERFLOW_ANSWER = StackOverflowAnswer.STACK_OVERFLOW_ANSWER;

    /**
     * The table <code>STACK_OVERFLOW_COMMENT</code>.
     */
    public static final StackOverflowComment STACK_OVERFLOW_COMMENT = StackOverflowComment.STACK_OVERFLOW_COMMENT;

    /**
     * The table <code>STACKOVERFLOW_INFO</code>.
     */
    public static final StackoverflowInfo STACKOVERFLOW_INFO = StackoverflowInfo.STACKOVERFLOW_INFO;

    /**
     * The table <code>TRACKED_LINK</code>.
     */
    public static final TrackedLink TRACKED_LINK = TrackedLink.TRACKED_LINK;

    /**
     * The table <code>WEBSITE_INFO</code>.
     */
    public static final WebsiteInfo WEBSITE_INFO = WebsiteInfo.WEBSITE_INFO;

    /**
     * The table <code>WEBSITE_INFO_TYPE</code>.
     */
    public static final WebsiteInfoType WEBSITE_INFO_TYPE = WebsiteInfoType.WEBSITE_INFO_TYPE;
}
